import styled from 'styled-components';

const About=styled.div `
display:grid;
grid-template-columns:repeat(12,8.333vw);
grid-auto-rows:minmax(1vw,auto);
.portrait{
    grid-column:2/12;
    grid-row:1/2;
    width:380px;
    max-width:100%;
    margin:auto;
    }
.head{
    grid-column:2/12;
    grid-row:2/3;
};
.about{
    grid-column:2/12;
    grid-row:3/4;
};
.offer{
    grid-column:2/12;
    grid-row:4/5;
};
.quote{
    grid-column:2/12;
    grid-row:6/7;
    font-style:italic;
};
.awards{
    grid-column:2/12;
    grid-row:5/6;
    img{max-width:150px;}
}
@media only screen and (min-width:900px) {
    .portrait{
    grid-column:7/12;
    grid-row:1/4;
    }
.head{
    grid-column:2/6;
    grid-row:1/2;
};
.about{
    grid-column:2/6;
    grid-row:2/3;
};
.offer{
    grid-column:2/6;
    grid-row:3/4;
};
.awards{
    grid-column:2/12;
    grid-row:5/6;
    figcaption{padding-top:60px;
    text-align:center;}
    img{
        float:left;
    }
}
.quote{
    padding-top:50px;
    grid-column:2/12;
    grid-row:6/7;
    font-style:italic;
};
    
}
@media only screen and (min-width:1500px) {
    .portrait{
    grid-column:7/10;
    grid-row:1/4;
    }
.head{
    grid-column:3/6;
    grid-row:1/2;
};
.about{
    grid-column:3/6;
    grid-row:2/3;
};
.offer{
    grid-column:3/10;
    grid-row:4/5;
};
.awards{
    grid-column:3/10;
    grid-row:5/6;
}
.quote{
    grid-column:3/10;
    grid-row:6/7;
    font-style:italic;
};
    
}
`
export{About}